version: '3.8'

services:
  postgres:
    image: postgres
    container_name: fleet-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecs
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
    - backend
volumes:
      postgres_data:
networks:
      backend:
